### ISSUE TITLE
the RFC should let subscribed readers test a reference implementation when possible

### ISSUE THREAD

**Issue by kapouer** [ProseMirror/rfcs#2]
So maybe the template could leave some room for giving a github fork that we could test.

**Comment by marijnh** [comment]
I think this would be best linked in the PR description text, rather than the RFC, since those are supposed to be more or less formal documents that stay descriptive in the future--links to such forks are bound to be outdated. In patch 1169d90 I've added a PR template that encourages people to add such links.
